### ISSUE TITLE
koa-meta: figure out why tests fail after upgrading dependencies

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/bug-bounties#8]
I upgraded all deps in `koa-meta` and the tests now seem to fail

https://github.com/ladjs/koa-meta

**Comment by fl0w** [comment]
It's actually not the deps change that broke tests, but instead the [commit before](https://github.com/ladjs/koa-meta/commit/1f9e598d8e2d64bfb5be339be89556bcd7897c60), "Fixed error throwing".

So that commit catches the throw and doesn't re-throw which both failing tests expects.

The fix is to either `$ git revert 1f9e598` which would,

```diff
diff --git a/index.js b/index.js
index ca9f81c..f1a12ed 100644
--- a/index.js
+++ b/index.js
@@ -78,12 +78,7 @@ class Meta {
     //
     // this has built in support for @ladjs/i18n
     // since it exposes `ctx.pathWithoutLocale`
-    let data = {};
-    try {
-      data = this.getByPath(ctx.pathWithoutLocale || ctx.path, ctx.req.t);
-    } catch (err) {
-      data = this.getByPath('/', ctx.req.t);
-    }
+    const data = this.getByPath(ctx.pathWithoutLocale || ctx.path, ctx.req.t);
     Object.assign(ctx.state, { meta: {} });
     Object.assign(ctx.state.meta, data);
     return next();
```

Or one would need to bump semver accordantly for updated behaviour (is I understand it, said commit is a breaking change).

**Comment by niftylettuce** [comment]
Thanks for the find @fl0w - what is your PayPal?

**Comment by niftylettuce** [comment]
Feel free to email it privately to niftylettuce@gmail.com

**Comment by niftylettuce** [comment]
Thank you so much.  I sent you a message in Slack regarding payout, and truly appreciate your generosity in time.
